apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-app: devops-sa
  name: devops-sa
  namespace: myproject
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: project-devops-sa
  namespace: myproject
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: devops-sa
subjects:
- kind: ServiceAccount
  name: devops-sa
  namespace: myproject
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: project-devops-sa-aws
  namespace: myproject
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: devops-sa
subjects:
  - kind: Group
    name: project:devops-sa
    namespace: myproject
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-app: spark-admin
  name: spark-admin
  namespace: spark-operator
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: project-spark-admin-sa
  namespace: spark-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spark-admin
subjects:
- kind: ServiceAccount
  name: spark-admin
  namespace: spark-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: project-spark-admin-aws
  namespace: spark-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spark-admin
subjects:
  - kind: Group
    name: project:spark-admin
    namespace: spark-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-app: kafka-admin
  name: kafka-admin
  namespace: kafka
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: project-kafka-admin-sa
  namespace: kafka
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kafka-admin
subjects:
- kind: ServiceAccount
  name: kafka-admin
  namespace: kafka
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: project-kafka-admin-aws
  namespace: kafka
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kafka-admin
subjects:
  - kind: Group
    name: project:kafka-admin
    namespace: kafka
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: project-apigw-admin-sa
  namespace: apigw
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: apigw-admin
subjects:
- kind: ServiceAccount
  name: apigw-admin
  namespace: apigw
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: project-apigw-admin-aws
  namespace: apigw
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: apigw-admin
subjects:
  - kind: Group
    name: project:apigw-admin
    namespace: apigw
---
